- .babelrc
- README.md
- package-lock.json
- package.json
- src/App/App.js
- src/App/Tester/Tester.js
- src/App/Tester/index.js
- src/main.js
- webpack.dev.js
This PR adds some initial Zooniverse-focused components to our custom front end.
- Grommet + Zooniverse Grommet theme installed. We now look snazzy.
- `@zooniverse/react-components` installed. (See [FEM PR 3995](https://github.com/zooniverse/front-end-monorepo/pull/3995) for what it took to get this to work.)
- `@zooniverse/panoptes-js` installed. We can now ping the Panoptes and Talk API endpoints.
- New Tester Component added, to test sending search queries to the Zooniverse Talk API
- 📄 Documentation: added "Developer Notes" to document scope and lifespan of this project.
- Misc: optional chaining (`something?.prop`) enabled on Babel.
> Add Zooniverse components

- jest.config.json
Merge target: PR #4
This PR fixes Jest tests. Prior to this PR, the tests were breaking because they didn't recognise the Webpack alises, e.g. `@src/App/Tester` is supposed to map to `(root)/src/App/Tester`
- Solution was to use Jest's `ModuleNameMapper` [config option](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring).
- See [Jest documentation on working with webpack.](https://jestjs.io/docs/webpack)
> Fix Jest: sync with Webpack aliases

- .github/workflows/build_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/run_tests.yml
- README.md
- jest.config.json
- webpack.dev.js
This PR adds GitHub Actions to the repo.
- New: the project can be deployed via Slack's bot commands, to `https://community-catalog.zooniverse.org/`
- Note: requires https://github.com/zooniverse/static/pull/318
- New: when a PR branch is created, a build automatically runs.
Dev notes: templates used were [Classrooms's actions](https://github.com/zooniverse/classroom/tree/master/.github/workflows). Initially I used [Zoo Notes](https://github.com/zooniverse/zoo-notes/tree/master/.github/workflows) since that had a more recent update, but that repo's using `yarn` and React Create App.
I still need to figure out those TODOs, but this PR is pretty safe to review on its own. I might merge this "deploy actions" first then solve the "run tests action" separately (because I need to debug some …
> Add GitHub Actions for PR builds and production deploys

- .github/workflows/build_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/run_tests.yml
- Build and deploy with Node 18 LTS (`lts/hydrogen`.)
- Run the tests, and a test Webpack build, on Node 18.
> Build with Node 18 LTS

- package.json
- webpack.dev.js
This is a small miscellaneous fix.
- After the introduction of Node 18 in recent updates, the Webpack dev server for local development no longer allows us to view the website via `local.zooniverse.org:8080`, insisting that this has to be `localhost:8080`
- Solution to this was to remove the specific `host` from webpack config
- Additionally, package.json now specifies the required Node and npm versions, for local development.
> Fix localhost for dev server & specify Node ver

- package-lock.json
- package.json
- src/App/App.js
- src/App/App.spec.js
- src/App/common/Header/Header.js
- src/App/pages/SearchPage/SearchPage.js
- src/App/pages/SearchPage/index.js
- src/App/pages/SubjectPage/SubjectPage.js
- src/App/pages/SubjectPage/index.js
- src/main.js
- src/router.js
- webpack.dev.js
This PR adds pages, and routing logic.
- New dependency: `react-router-dom` v6
- ⭐  **Webpack Dev Server update:** historyApiFallback and publicPath added.
- This allows webpack dev server to perform some URL rewriting (rerouting?), so `localhost:8080/my/path` can be handled by the base /index.html instead of returning a 404. The old alternative was to use `localhost:8080/#/my/path`.
- New pages:
- `/` - home page (placeholder)
- `/search` - search page (placeholder)
- `/subject/{subjectID}` - subject page (placeholder)
- Old tester code cleaned up
> Pages and Routing

- src/components/KeywordsList/KeywordsList.js
- src/components/SearchResultsList/SearchResult.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectKeywords/SubjectKeywords.js
- src/components/SubjectMetadata/SubjectMetadata.js
- src/helpers/fetchKeywords.js
- src/helpers/fetchSubject.js
- src/helpers/fetchTagSearchResults.js
- src/pages/HomePage/HomePage.js
- src/projects.json
Follows #77
Followup PR! Seems like a missed a few bugs in the previous update that added multi-project support, and while I was at it, I threw in some additional improvements.
- Project Improvements (Project Config):
- Each project can now have its own "example subjects" that are shown on its home page.
- Each project can now have its own "example query" that populates the search results on its home page. (This replaces the hardcoded query of "tables", which only made sense for Scarlets & Blues)
- Each project can now designate one of its metadata fields as its "title field". (This replaces the "Lorem Ipsum" text on each Subject Item in the search results list)
- Other Improvements: fetch functions now stop executing if no Project ID is given
- Fixes:
- KeywordsList, SearchResultsList, …
> Fix Multiple Projects

- src/components/ProjectContainer/ProjectContainer.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/Tester/Tester.js
- src/helpers/fetchDatabaseSearchResults.js
- src/helpers/fetchSearchResults.js
- src/helpers/fetchSearchResults_fromDatabase.js.js
- src/helpers/fetchSearchResults_fromTalk.js
- src/helpers/fetchTalkSearchResults.js
- src/pages/HomePage/index.js
- src/pages/ProjectPage/ProjectPage.js
- src/pages/ProjectPage/index.js
- src/router.js
This PR adds _database search functionality_ to the Community Catalog.
- New behaviour:
- when typing in a search query, the CC now searches both **Talk** and the (Subject Set Search API) **Database**
- Code changes:
- fetchSearchResults() now consolidates the fetch actions, and removes duplicates. Oh, also we only care about getting Subject IDs, not the full resources.
- fetchTalkSearchResults() and fetchDatabaseResults() renamed.
- HomePage renamed to ProjectPage. We still need a root home page.
- ⚠️ Pagination hasn't come up yet, but will become an issue once we have a larger amount of Subjects.
Ready to go!
> Add Database search results

- src/components/AdvancedSearchForm/AdvancedSearchForm.js
- src/components/AdvancedSearchForm/index.js
- src/components/Header/Header.js
- src/components/Link/Link.js
- src/components/RandomButton/RandomButton.js
- src/components/SearchResultsList/SearchResultsList.js
- src/config.js
- src/helpers/convertAdvancedQueryFromString.js
- src/helpers/convertAdvancedQueryToString.js
- src/helpers/fetchSearchResults.js
- src/helpers/fetchSearchResults_fromDatabase.js
- src/helpers/getQuery.js
- src/pages/ProjectPage/ProjectPage.js
- src/pages/SearchPage/SearchPage.js
- src/projects.json
- src/strings.json
This PR adds advanced search functionality to the Community Catalog. Previously, only simple searches were supported,
Explanation: a simple search will search _every_ field of a Subject's metadata + Talk keywords for a matching word, e.g. `"cat"`. An advanced search looks for specific values in specific fields, e.g. `"{animal=cat} {color=orange} {loves=lasagna} {hates=mondays}"`
- ⭐ Advanced Search functionality added:
- A whole bunch of functions added to parse/unparse advanced search query objects from/to strings.
- fetchSearchResults() now switches between simple and advanced searches depending on the query string
- AdvancedSearchForm component added.
- projects.json updated, allowing the advanced search form for each project to be configured.
- Tweaks:
- …
> Advanced Search

- package-lock.json
- package.json
- src/components/AdvancedSearchForm/AdvancedSearchForm.js
- src/components/Header/Header.js
- src/components/KeywordsList/KeywordsList.js
- src/components/ProjectContainer/ProjectContainer.js
- src/components/RandomButton/RandomButton.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectActionsPanel/SubjectActionsPanel.js
- src/components/SubjectActionsPanel/index.js
- src/components/SubjectDiscussion/SubjectDiscussion.js
- src/components/SubjectDiscussion/index.js
- src/components/SubjectImage/SubjectImage.js
- src/components/SubjectKeywords/SubjectKeywords.js
- src/components/SubjectMetadata/SubjectMetadata.js
- src/components/SubjectViewer/SubjectViewer.js
- src/components/SubjectViewer/index.js
- src/pages/ProjectPage/ProjectPage.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SubjectPage/SubjectPage.js
- src/projects.json
- src/strings.json
This PR improves the Subject page.
- SubjectPage:
- Various UI stylings updated to match Sean's designs.
- Now we're using CSS grids! Grids for everyone!
- Various subcomponents now have a "data placeholder" icon when the subject data isn't available or is loading.
- SubjectViewer: new component replicates SubjectImage, but with a filmstrip viewer to switch between subject images.
- SubjectActionsPanel: new component allows users to Classify This Subject.
- Other functionality (add to faves, add to collection, share) haven't been implemented.
- Installed styled-components.
- How did I forget to install this before, and how did has it been working?!? (ans: apparently the ZRC dependency installed styled-components)
- Also we're using styled-components v5 instead of the latest v6 to avoid …
> Subject page

- package.json
- src/index.html
- webpack.prod.js
Fixes #113 
This PR fixes the issue where https://community-catalog.zooniverse.org/ keeps serving users (up to a week old) cached pages, because the `main.js` file didn't have any hashes in the filename to ensure consistently new files being served.
Build changes:
- Output file, `main.js`, is now `main.{HASH}.js`
- Index.html now contains commit ID, build time, and build environment, to assist with debugging.
These build config settings should have been standard for all our Zooniverse static CFEs, so I'm putting them in now. Thanks to Michelle, Zach, and Jim for pointers on this. 👍
> Fix cached pages

- src/pages/SubjectPage/SubjectPage.js
- src/projects.json
This PR adds the ["How Did We Get Here?"](https://frontend.preview.zooniverse.org/projects/communitiesandcrowds/how-did-we-get-here) Zooniverse project to the Community Catalog. HDWGH is (one of?) the main project(s?) under the larger Communities & Crowds project, so we're finally reaching the "ready to go live" stage
- Project URL will be: https://community-catalog.zooniverse.org/projects/communitiesandcrowds/how-did-we-get-here
- Note that HDWGH's metadata fields differs slightly from the "Community Catalog (Stable Test Project)" test project, and includes some typos. Ah well! We'll see what happens if/when newer subjects correct/change those fields.
Associated external updates:
- HDWGH was also added to the Subject Set Search API.
- See …
> Add "How Did We Get Here?" project

- src/components/Header/Header.js
- src/components/Tester/Tester.js
- src/pages/SearchPage/SearchPage.js
This PR is a small tweak to the UX: the header search field now shows/retains the search queries from users, i.e. it displays the value of the `?query=...`
Previously, every time a user executes a search, the search field would reset to blank.
> Header search now shows/retains queries

- src/components/SearchResultsList/SearchResult.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectImage/SubjectImage.js
- src/config.js
- src/strings.json
Follows #125 
This PR changes the layout for the Search Results List to more closely match the current design.
- By default, search results are now left-aligned instead of center-aligned.
- On narrow views, search results are center-aligned.
- The size of "Search Result" items has been tweaked so there's less "dead space" on the right at optimal viewport widths.
> Search Results List: left-align, plus narrow view

- src/App/App.js
- src/components/Header/Header.js
- src/components/KeywordsList/KeywordsList.js
- src/components/ProjectContainer/ProjectContainer.js
- src/components/RandomButton/RandomButton.js
- src/components/SearchResultsList/SearchResult.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectImage/SubjectImage.js
- src/components/SubjectKeywords/SubjectKeywords.js
- src/components/SubjectViewer/SubjectViewer.js
- src/helpers/fetchKeywords.js
- src/helpers/fetchRandomSubjects.js
- src/helpers/fetchSearchResults.js
- src/helpers/fetchSearchResults_fromDatabase.js
- src/helpers/fetchSearchResults_fromTalk.js
- src/helpers/fetchSubject.js
- src/pages/ProjectPage/ProjectPage.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SubjectPage/SubjectPage.js
This PR is a major overhaul/refactor that has very minimal functional changes.
In General:
- Anonymous functions used in useEffect()s are now named. Usually in a `onTrigger_doSomething()` format.
- Fetch functions now eschew the 'setData(results)' pattern, and instead just return the results. Consequently, components have been rewritten to use async `doFetchData()` functions
- Components that fetch data (e.g. SearchResult, SubjectImage, SubjectPage, KeywordsList, SubjectKeywords) now keep track of the fetching status (READY/FETCHING/ERROR) and - in most cases - display that status on the UI in some form.
UI changes:
- SubjectPage: now displays error message in h2 header, if something borks.
- SubjectImage and SearchResult: NO changes, actually. Whether the subject is being fetched, or has …
> Fix useEffects and add fetch UI

- src/components/KeywordsList/KeywordsList.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectMetadata/SubjectMetadata.js
- src/helpers/fetchSearchResults.js
- src/helpers/removeDuplicates.js
- src/pages/HomePage/HomePage.js
- src/pages/SubjectPage/SubjectPage.js
- src/projects.json
This is PR contains multiple small functionality tweaks
Project config update:
- Add `metadata_fields_aliases`, `hidden`, `keywords_to_always_suggest`, and `keywords_to_never_suggest` fields
- Community Catalog (Stable Testing Project) now uses the new fields to demonstrate how they can be used.
- HDWGH now has keywords to never suggest, and a metadata field alias.
- Both testing projects now set to hidden
Components update:
- HomePage now doesn't show projects marked as 'hidden'
- KeywordsList will now always have keywords marked "always suggest", and will never show keywords marked "never suggest"
- SubjectMetadata now displays the alias of any metadata field, if such an alias exists.
Other:
- `removeDuplicates()` helper function added. Does exactly what it says.
> Functionality Tweaks

- src/components/SubjectDiscussion/SubjectDiscussion.js
- src/helpers/getQuery.js
- src/projects.json
- src/router.js
The addition of the Markdownz in `<SubjectDiscussion>`'s `<Comment>`s introduced a new problem. When a user types in hashtag keywords (for example, `#Jamaica`), the Markdownz component automatically turns that hashtag into a link _back to the Zooniverse Talk pages._ (For example, https://frontend.preview.zooniverse.org/projects/darkeshard/community-catalog/talk/search?query=#jamaica or https://frontend.preview.zooniverse.org/projects/darkeshard/community-catalog/talk/tags/jamaica)
This PR fixes the issue by redirecting those links back to the Community Catalog's search page.
- SubjectDiscussion/Comment: Markdownz's new "baseURL" is now set to the Community Catalog, instead of the Project's Zooniverse Talk page.
- Router: any visits to `(project)/talk/search` (i.e. the links created by …
> Redirect Talk hashtag links

- src/components/Footer/Footer.js
Follows #141
Whoops, I just realised there were some flaws with the footer I updated previously.
- Apparently, the footer was being rendered as 'header' instead of 'footer'. That's a high quality DERP right there.
- 0.75em font size wasn't triggering properly; I shouldn't have tried to style the Markdownz component.
- Layout has been centre-aligned and max-width-ed to match the Landing Page's intro text. Because having no max-width makes the now long footer text cover way too much of the screen.
> Footer: content update pt2

- README.md
This PR updates the documentation with an Operations section. This should (hopefully) provide Zooniverse devs enough info on how to perform standard content updates and content maintenance, such as how to add new projects and how to test if everything is working.
> Readme: add Operations section

- jest/jest-setup.js
- package-lock.json
- package.json
- webpack.prod.js
`@zooniverse/react-components` 1.9.0 is broken, so this pulls the changes out of #213 that are needed to run 1.8.1.
> Bump @zooniverse/react-components to 1.8.1

- src/projects.json
This PR adds the Stereovision project to the Community Catalog.
- As the project is still in development, it's hidden from the home page.
- To access the project on the Community Catalog, use this URL: https://community-catalog.zooniverse.org/projects/juliehgibb/stereovision/
- Alternatively, on localhost: https://local.zooniverse.org:8080/projects/juliehgibb/stereovision/?env=production
See also:
- Stereovision added to the Subject Set Search API: https://github.com/zooniverse/subject-set-search-api/pull/68 and https://github.com/zooniverse/subject-set-search-api/pull/69
Also in this PR:
- 🛠️ FIX: "How Did We Get Here"'s **Classify links** now take users to the full Zooniverse URL, instead of the FEM preview URL.
Context: the Stereovision project is the second project to be supported on …
> Add Stereovision project

- src/components/ProjectContainer/ProjectContainer.js
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SubjectActionsPanel/SubjectActionsPanel.js
- src/components/SubjectViewer/SubjectViewer.js
- src/components/WorkflowSelectionDialog/WorkflowSelectionDialog.js
- src/components/WorkflowSelectionDialog/index.js
- src/helpers/fetchProjectData.js
- src/pages/SubjectPage/SubjectPage.js
- src/projects.json
- src/store/AppStore.js
- src/strings.json
With addition of the "Stereovision" project (#251), the Community Catalog now needs to support projects that have multiple workflows. (The previous project, "How Did We Get Here?", only had one.)
- New behaviour, on Subject Page:
- (no change) on a single workflow project, when clicking on "Classify this Project",  the user is immediately taken to the FEM Classify page on www.zooniverse.org
- 🆕 on a multi workflow project, when clicking on "Classify this Project", the Workflow Selection Dialog (modal) pops up
-  clicking on a workflow in the modal then takes the user to the FEM Classify page on www.zooniverse.org
- New component: Workflow Selection Dialog
- Lists all workflows available in a project.
- Can be closed by either clicking outside modal, or pressing Esc.
- ⚠️ Needs a design …
> Support multiple workflows for "Classify This Subject"

- src/components/Header/ProjectHeader.js
- src/components/RandomButton/RandomButton.js
- src/components/SubjectViewer/SubjectViewer.js
- src/config.js
- src/pages/SubjectPage/SubjectPage.js
Follows #253
Figma Design: https://www.figma.com/design/tidtkbpbLYV3p8a2kDy0db/Community-Catalog?node-id=0-1&t=86hSbdjluVHgl5Ul-0
<details>
<summary>(preview)</summary>
</details>
This PR updates the UI of the Community Catalog to better match Sean's design updates from 8 Jul 2024 [(Slack)](https://zooniverse.slack.com/archives/C01MD17KBNW/p1720458107961289). In this PR, I'm updating the SubjectPage design.
- SubjectPage:
- Layout changed.
- Subject Title (h2) removed. (An error message will still appear at its place if e.g. you try to view a Subject that doesn't exist.)
- Subject Actions Panel (Favourite, Share, Classify this Subject, etc) removed.
- SubjectViewer:
- Now has a  "Subject Details" subcomponent, which contains the now-moved Subject Title (not a h2) and Classify This Subject …
> Jul 2024 Design Update: Subject Page

- src/components/Header/HeaderSearchForm.js
- src/components/Header/ProjectHeader.js
- src/components/SubjectDiscussion/SubjectDiscussion.js
- src/components/SubjectKeywords/SubjectKeywords.js
- src/components/SubjectMetadata/SubjectMetadata.js
- src/config.js
- src/index.html
- src/pages/ProjectPage/ProjectPage.js
- src/pages/SubjectPage/SubjectPage.js
Follows #254 
Figma Design: https://www.figma.com/design/tidtkbpbLYV3p8a2kDy0db/Community-Catalog?node-id=0-1&t=86hSbdjluVHgl5Ul-0
<details>
<summary>(preview)</summary>
</details>
This PR updates the UI of the Community Catalog to better match Sean's design updates from 8 Jul 2024 [(Slack)](https://zooniverse.slack.com/archives/C01MD17KBNW/p1720458107961289). In this PR, I'm updating the ProjectPage design, alongside with misc layout-related tweaks based on a design discussion on [Slack.](https://zooniverse.slack.com/archives/C01MD17KBNW/p1723131041252059)
- ProjectPage:
- Remove Random Button under carousel
- Carousel tweaks
- Layout, General:
- Main layout's max width increased to 1440px
- Layout on mobile devices corrected (I forgot the viewport meta)
- Layout, ProjectHeader:
- Remove …
> Jul 2024 Design Update: Project Page and misc Layout

- src/components/SearchResultsList/SearchResult.js
- src/components/SubjectViewer/SubjectViewer.js
- src/helpers/getSubjectTitle.js
- src/projects.json
Follow #257 and https://github.com/zooniverse/subject-set-search-api/pull/73
In the Community Catalog, every Subject has a "title" that's taken from its metadata. This makes a few assumptions:
- the metadata has a field that can more or less describe the subject.
- this field has a consistent _field name_ across every subject
Alas, some projects have Subjects that are inconsistent with the CAPITALisations of their FiEld nAMes, so our previous method of doing something like `title = subject.metadata[project.title_field]` doesn't always work.
This PR solves the issue by adding the getSubjectTitle() helper, which compensates by ignoring the upper/lower case of field names.
Also, the Stereovision proejct's title field is now `object_number` (or `Object_Number` in some cases) instead of …
> Add getSubjectTitle() to handle Subjects with inconsistent Captalisations in their fIelD NaMes

- src/README.md
- src/components/ProjectContainer/ProjectContainer.js
- src/components/SubjectViewer/SubjectViewer.js
- src/components/WorkflowSelectionDialog/WorkflowSelectionDialog.js
- src/helpers/fetchWorkflows.js
- src/pages/SubjectPage/SubjectPage.js
- src/projects.json
- src/store/AppStore.js
- src/strings.json
Our recent experience with the Stereovision project has highlighted the following issues:
- Workflows can be activated and/or inactivated without warning, causing a mismatch in hardcoded project configs.
- Subjects can be de-associated from workflows, making them impossible to Classify (i.e. the subject sets they belong to can be de-associated from active workflows, such as the case with beta test Subjects)
This PR attempts to address the issues above by pulling live _active Workflow_ data for a given Project, and ensuring a Subject "belongs" to at least one active 
- ProjectContainer and AppStore:
- now fetches all **active workflows** belonging to a Project.
- Note: this data fetch is considered secondary, and won't block the app from running while it's still ongoing in the background. …
> "Classify this Subject" feature: use live active Workflow data
